### ISSUE TITLE
Expose `min` and `max` attributes on the `input` element

### ISSUE THREAD

**Issue by Turbo87** [qonto/ember-amount-input#151]
When we want to contrain the user in what values he can enter it will be useful to set the `min` and `max` values on the `<input>` element, but it looks like these are not exposed as arguments for this component yet.

**Comment by LukaM17** [comment]
@dbendaou Can i try to solve this issue ?

**Comment by dbendaou** [comment]
Yeah sure!

**Comment by hakilebara** [comment]
Thank you @rasha-essam
